version: "3.8"

services:
    bizfly-mcp-server:
        build:
            context: .
            dockerfile: Dockerfile
        image: bizfly-mcp-server:latest
        container_name: bizfly-mcp-server
        restart: unless-stopped
        environment:
            # Required environment variables
            - BIZFLY_USERNAME=${BIZFLY_USERNAME}
            - BIZFLY_PASSWORD=${BIZFLY_PASSWORD}
            # Optional environment variables with defaults
            - BIZFLY_REGION=${BIZFLY_REGION:-HaNoi}
            - BIZFLY_API_URL=${BIZFLY_API_URL:-https://manage.bizflycloud.vn}
        stdin_open: true
        tty: true
        # For MCP server, stdio communication is handled automatically
        # stdin_open: true and tty: true enable stdin/stdout/stderr forwarding
        # No need to mount /dev/stdin, /dev/stdout, /dev/stderr as volumes
